# coding: utf-8

EPISODE_LENGTH = 30
DATA_BUFFER_SIZE = 20000

SIM_ROUNDS = 1000  # total sample size: SIM_ROUNDS * EPISODE_LENGTH
SIM_BATCH_SIZE = 50
SIM_ROUNDS_PER_STEP = 23

IMPROVE_STEPS_PER_EPOCH = 100
IMPROVE_BATCH_SIZE = 2048

VALID_ROUNDS = 100
VALID_ROUNDS_PER_STEP = 23
VALID_INTERVAL = 600

CURRENT_MODEL_FILE = 'model.current'

CPU_CORES = 2
